import datetime
import os
import random
from pathlib import Path

import modal
from dotenv import load_dotenv

# seed
RANDOM_SEED = 42
random.seed(RANDOM_SEED)

# paths
PARENT_PATH = Path(__file__).parent.parent
DB_SRC_PATH = PARENT_PATH / "db"
SRC_PATH = PARENT_PATH / "src"

# options
LOGIN_TYPES = ["github", "google", "email"]
MAJORS = [
    # College of Arts and Sciences
    "Anthropology",
    "Art History",
    "Biochemistry",
    "Biology",
    "Chemistry",
    "Child Studies",
    "Classical Studies",
    "Communication",
    "Computer Science",
    "Economics",
    "Engineering Physics",
    "English",
    "Environmental Science",
    "Environmental Studies",
    "Ethnic Studies",
    "French and Francophone Studies",
    "History",
    "Individual Studies",
    "Italian Studies",
    "Mathematics",
    "Music",
    "Neuroscience",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health Science",
    "Religious Studies",
    "Sociology",
    "Spanish Studies",
    "Studio Art",
    "Theatre Arts",
    "Women's and Gender Studies",
    # Leavey School of Business
    "Accounting",
    "Accounting & Information Systems",
    "Economics",
    "Finance",
    "Management",
    "Marketing",
    "Operations and Management Information Systems",
    # School of Engineering
    "Bioengineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Electrical and Computer Engineering",
    "Electrical Engineering",
    "General Engineering",
    "Mechanical Engineering",
    "Web Design and Engineering",
]
MINORS = [
    # College of Arts and Sciences
    "Anthropology",
    "Art History",
    "Asian American Studies",
    "Asian Studies",
    "Biology",
    "Catholic Studies",
    "Chemistry",
    "Classical Studies",
    "Communication",
    "Computer Science",
    "Creative Writing",
    "Dance",
    "Digital Filmmaking",
    "Economics",
    "English",
    "Environmental Studies",
    "Ethnic Studies",
    "French and Francophone Studies",
    "German Studies",
    "Gerontology",
    "Graphic Design",
    "History",
    "Italian Studies",
    "Japanese Studies",
    "Journalism",
    "Latin American Studies",
    "Mathematics",
    "Medieval and Renaissance Studies",
    "Music",
    "Musical Theatre",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Religious Studies",
    "Sociology",
    "Spanish Studies",
    "Studio Art",
    "Sustainability",
    "Theatre",
    "Urban Education",
    "Women's and Gender Studies",
    # Leavey School of Business
    "Accounting",
    "Economics",
    "Entrepreneurship",
    "Finance",
    "Information Systems",
    "International Business",
    "Management",
    "Marketing",
    "Real Estate",
    # School of Engineering
    "Aerospace Engineering",
    "Bioengineering",
    "Civil Engineering",
    "Computer Science and Engineering",
    "Electrical and Computer Engineering",
    "General Engineering",
    "Mechanical Engineering",
    "Web Design and Engineering",
]
GRADUATION_YEARS = [datetime.datetime.now().year + i for i in range(5)]
INTERESTS = [
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Statistics",
    "Mathematics",
    "Social Justice",
    "Environmental Sustainability",
    "Global Business",
    "Entrepreneurship",
    "Innovation",
    "Silicon Valley Technology",
    "Healthcare",
    "Biomedical Engineering",
    "Computer Science",
    "Software Development",
    "Web Design",
    "Finance",
    "Marketing",
    "Accounting",
    "Economics",
    "Management",
    "Ethics",
    "Biochemistry",
    "Psychology",
    "International Relations",
    "Public Policy",
    "Education",
    "Arts",
    "Theatre",
    "Music",
    "Literature",
    "Philosophy",
    "Religious Studies",
    "Cultural Studies",
    "Research",
    "Law",
    "Public Health",
    "Medicine",
    "Communications",
    "Journalism",
    "Media Studies",
    "Community Service",
    "Leadership",
    "Consulting",
    "Venture Capital",
]
PERSONALITY_TRAITS = [
    "Introverted",
    "Extroverted",
    "Sensing",
    "Intuitive",
    "Thinking",
    "Feeling",
    "Judging",
    "Perceiving",
    "Analytical",
    "Creative",
    "Detail-oriented",
    "Big-picture",
    "Ambitious",
    "Adaptable",
    "Collaborative",
    "Independent",
    "Persistent",
    "Flexible",
    "Empathetic",
    "Logical",
    "Innovative",
    "Traditional",
    "Risk-taking",
    "Cautious",
    "Organized",
    "Spontaneous",
    "Competitive",
    "Cooperative",
    "Reflective",
    "Action-oriented",
    "Patient",
    "Decisive",
    "Open-minded",
    "Focused",
    "Compassionate",
    "Strategic",
    "Resilient",
    "Conscientious",
    "Curious",
    "Diligent",
]

# Modal
APP_NAME = "bronco-buddies"
IN_PROD = os.getenv("MODAL_ENVIRONMENT", "dev") == "main"
load_dotenv(".env.local")
SECRETS = [
    modal.Secret.from_dotenv(
        path=PARENT_PATH,
        filename=".env" if IN_PROD else ".env.dev",
    )
]

MINUTES = 60  # seconds
PYTHON_VERSION = "3.12"
